### ISSUE TITLE
Scalaz 8 Roadmap

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz#1526]
# Checklist

 - [ ] **Core**
    - [ ] **Type**
      - [x] **Leibniz**
      - [x] **Liskov**
      - [ ] **AList**
      - [ ] ...
    - [ ] **Data**
      - [ ] **List**
      - [x] **Maybe**
      - [x] **Disjunction**
      - [ ] **Map**
      - [ ] ...
    - [ ] **Functor Hierarchy**
      - [ ] ...
    - [ ] **MTL**
      - [ ] ...
    - [ ] **Algebra**
      - [ ] ...
    - [ ] **Other CT**
      - [ ] ...
 - [ ] **Syntax**
    - [ ] **Zero-cost, by-name syntax macros**
    - [ ] ...
 - [ ] **Effect**
    - [x] **IO**
    - [x] **MVar**
    - [x] **RTS**
    - [ ] **MonadIO**
    - [ ] **MonadFork**
    - [ ] **MonadBracket**
    - [ ] **STM**
    - [ ] **TVar**
    - [ ] ...
 - [ ] **Example**
    - [ ] ...
 - [ ] **Test**
    - [ ] ...
 - [ ] **Benchmark**
    - [x] scalaz.effect.IO
    - [ ] scalaz.effect.MVar
 - [ ] **Design Guide**

# Overview

### Data

**Needed**: Someone to spearhead this work.

### Functor Hierarchy

The Scalaz 8 functor hierarchy needs to be modularized to minimize the number of new abstractions needed to capture distinctions between different types of functors.

While the scope and nature of these changes is TBD, one useful suggestion by @ekmett is to factor out `Productive` and `Coproductive` classes:

```scala
trait Productive[F[_]] {
  def product[A, B](fa: F[A], fb: F[B]): F[(A, B)]
  def unit: F[Unit]
}
```

```scala
trait Coproductive[F[_]] {
  def coproduct[A, B](fa: F[A], fb: F[B]): F[A \/ B]
  def counit: F[Void]
}
```

These abstractions permit more sharing between, for example, an invariant applicative and a covariant applicative, reducing the number of type class variations that would otherwise have to exist.

Similarly, modeling `Bind` as `F[F[A]] => F[A]` (rather than `(F[A], A => F[B]) => F[B])`) allows the question of arrow type to be deferred and isolated to `map` in the corresponding type of functor.

**Needed**: Someone to spearhead this work.

### MTL 

Type classes to describe all classes of effects. Unlike MTL, constraints should be minimized (e.g. `Functor` or `Apply` / `Applicative` when possible, `Monad` only when necessary), and as a result, names will differ substantially from Haskell.

While the type classes are essential, the dirty secret in Scala is that actual monad transformers do not perform and are not a realistic solution for most code. An alternative to stacks of monad transformers that is better suited to Scala must be developed.

**Needed**: Someone to spearhead this work.

### Algebra

**Needed**: Someone to spearhead this work.

## Effect 

**Lead**: @jdegoes 

## Benchmark

The benchmark package should help ensure Scalaz 8 encoding techniques, data structures, and effect systems are competitive with other techniques, up to the limits of the design goals.

## Design Guide

Scalaz 8 needs a design guide that can ensure uniform standards are followed.

 * Policies for laws — algebraic *and* operational
 * Policies for eager / lazy
 * Policies for variance (Invariance?)
 * Policies for polymorphic values (Pascal)
 * Policies for impure code
    * OK to accept if RT (e.g. lift into IO), not OK to return
 * Policies for `PartialFunction`
 * Detailed guide on type class encoding
 * Policies on native methods vs. extension methods
 * Detailed guide on syntax encoding

**Needed**: Someone to spearhead this work.

**Comment by jdegoes** [comment]
TODO: Port over [these notes](https://github.com/scalaz/scalaz/issues/1231) from @aloiscochard

**Comment by fommil** [comment]
Deriving will need iotaz if it is to be part of core, so perhaps best left as an addon module?

**Comment by TomasMikula** [comment]
Can you expand on this?

> Similarly, modeling `Bind` as `F[F[A]] => F[A]` (rather than `(F[A], A => F[B]) => F[B])`) allows the question of arrow type to be deferred and isolated to `map` in the corresponding type of functor.

**Comment by jdegoes** [comment]
@fommil Sure, it can live anywhere, although there are other reasons to consider including iotaz (composable error sets, for example). I view some of the other major areas as potentially existing elsewhere, in different repos.

@TomasMikula The current definition of `Bind` marries it to covariant functors. But if you modify the definition as suggested, then if you want a covariant monad, you combine `Functor` with `Bind`, and if you want an invariant monad, you combine `Invariant` with `Bind`.

**Comment by jdegoes** [comment]
Btw, to all Scalaz contributors: Please feel free to add to, edit, amend, and fill in!

**Comment by emilypi** [comment]
Have we enumerated what's going to be included in `data` yet, or is it, or do we just have `List` and `Map` outstanding currently

**Comment by Jacoby6000** [comment]
There's definitely a lot missing from that list.  I know for sure it is missing `OneAnd`, `NonEmptyList`, `These`/`Ior`, and some sort of Array backed collection.

**Comment by TomasMikula** [comment]
There was a proposal to have 2 versions of some data types: a direct, fast, but stack-unsafe encoding, and a slower but stack-safe encoding. Applies to e.g. `State` monad.

**Comment by jdegoes** [comment]
@TomasMikula We have discussed something even more radical, which is to not have the `State` monad at all, but only the type class `MonadState` or rather `ApplicativeState` (I suppose). Let's discuss sometime w/ @edmundnoble on the private http://gitter.im/scalaz channel.

**Comment by NeQuissimus** [comment]
Should we maybe convert the `example` project to use [tut](https://github.com/tpolecat/tut), so that Markdown can be used to explain certain pieces of code, thereby providing rich documentation?

**Comment by TomasMikula** [comment]
👍  for `tut`. Is there a way to automate the process of publishing tuts with every build?

**Comment by NeQuissimus** [comment]
I have only ever done this for an internal project (on GitHub Enterprise) and we have our build server build the documentation, then commit it into a separate repo, whose contents we expose via GitHub Pages. The separate repo was mostly to keep the tut commits out of our code history.

**Comment by jdegoes** [comment]
@NeQuissimus Sounds like a great idea. 👍

**Comment by caente** [comment]
Could you elaborate a bit more on the `Algebra` entry?

**Comment by jdegoes** [comment]
@caente I think this is a catch all for abstractions from abstract algebra, including things like `Semigroup`, `Lattice`, `Field`, and `Ring`. I have sketched some detail out above, and I think we can take inspiration from PureScript's hierarchy (and some work has been done in Scala, as well, in Spire and other libraries). Any interest in contributing to this one? 😁

**Comment by caente** [comment]
@jdegoes I was hopping you would say that. I'm definitely interested in contributing. From what you say it seems like there isn't even a _desired_ roadmap? I don't think my abstract algebra kung fu is enough for planing an strategy/hierarchy. 
Although perhaps it could be enough to "copy" PureScript as you said?
Do you have experience with Spire's algebra? Any reason for not follow a very similar path to theirs?

**Comment by vmarquez** [comment]
@caente would be awesome to have someone tackle this in depth!   One thing to keep in mind though is that it may make sense to tackle how we want to do laws first.   Algebraic structures such as  Group, Semigroup, Monoid, SemiLattice, etc. all look pretty similar with different laws... hence why when I added SemiLattice to 7.3.x, I didn't add to Scalaz8.  Food for thought. :)

**Comment by puffnfresh** [comment]
@caente copy PureScript

**Comment by dchenbecker** [comment]
Would improving scaladoc be considered part of "Examples"?

**Comment by jdegoes** [comment]
@caente I can definitely help out with that (as can others). As @puffnfresh says, starting with the PureScript hierarchy would be a good first step. It's not quite fine-grained enough but it has the right general shape. There is overlap with Spire but Spire contains "non-things" like `Trig` which would definitely not be desired in an abstract algebra package.

@dchenbecker I rewrote that section to be `Documentation`, which now contains Scaladoc, examples, and README.md. Any contributions to any of these would be enormously beneficial. 

Also: hi! 😄

**Comment by caente** [comment]
@jdegoes @puffnfresh I've been looking into purescript docs, and their algebra typeclasses seem to be distributed among several modules:
- https://pursuit.purescript.org/packages/purescript-prelude
- https://pursuit.purescript.org/packages/purescript-group
- https://pursuit.purescript.org/packages/purescript-monoid
I find strange that `Ring` and `Semigroup` are in prelude, but `Group` and `Monoid` and in different libs... wouldn't we want that `Ring` to be "composed" with abelian group and monoid, for example?

what would be the advantage of such non-hierarchical hierarchy?

**Comment by puffnfresh** [comment]
@caente Ring and Semigroup are there because that's where (+) and (-) come from. Prelude without (+) and (-) would be a bit weird! You'll also see Semiring and EuclideanRing for (*) and (/)

**Comment by puffnfresh** [comment]
@caente yeah, I think you're right, don't copy this part!

**Comment by caente** [comment]
thanks @puffnfresh, on the other hand this seems like a nice guide http://a-guide-to-the-purescript-numeric-hierarchy.readthedocs.io/en/latest/

I see, there a `Monoid` and `Semigroup`, so it seems to make sense to implement Group and abelian group, and then rings and fields?
but also, I don't see any `Monoid` or `Semigroup` instances in scalaz8, nor tests nor laws... am I missing something? why are they checked off?

Any thoughts on how to enforce laws? I see that in the current version of scalaz they are "built-in" on the typeclass itself, e.g. https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/Monoid.scala#L69-L82
I don't see any tests of that kind on scalaz8, is there a consensus about it?

btw I'd love to hear of _any_ use cases for these typeclasses...

**Comment by jdegoes** [comment]
@caente For now, I wouldn't worry about enforcing laws. The laws can be described in comments. Ultimately we want to add them as methods on the type classes, like Scalaz 7, but possibly closer to [what Cats is currently doing](https://github.com/typelevel/cats/blob/master/laws/src/main/scala/cats/laws/MonoidKLaws.scala), which is representing laws as data (`case class IsEq[A](lhs: A, rhs: A)`, with `<->` syntax for construction).

You are also right that PureScript makes some tradeoffs when it comes to the `Prelude` and also how fine-grained the hierarchy is. That's why we don't want to just copy wholesale, although it's a good place to start. See also the abstractions I posted above, [Algebra](https://hackage.haskell.org/package/algebra) (possibly the Gold Standard?), [Spire](http://github.com/non/spire), [Cats Algebra](https://github.com/typelevel/algebra/tree/master/core/src/main/scala/algebra), and of course [Wikipedia](https://en.wikipedia.org/wiki/Abstract_algebra) and [other](https://brilliant.org/wiki/abstract-algebra/) [free resources](http://www.paultaylor.eu/~pt/prafm/).

**Comment by jdegoes** [comment]
@caente I found Edward Kmett sketched out a hierarchy [here](https://github.com/ekmett/scala-numerics/tree/master/src/main/scala/numeric). It uses a someone non-idiomatic style of Scala but looks clean and well put together (Kmett also wrote Algebra for Haskell).

**Comment by caente** [comment]
@jdegoes last night I began implementing Group in terms of monoid, then I saw Kmett's code and I was intimidated and confused: The code seems bottomless. Hence I repeat the question I asked before: are there use cases we want to prioritize? I imagine we don't exactly want to use scalaz to proof theorems, but rather to automate certain operations?
I'm afraid I'm not the target audience for these typeclasses, but still wanna help.

**Comment by jdegoes** [comment]
@caente Well, let's start with something simple then:

 * Abelian
 * Commutative
 * Group
 * Loop
 * Magma
 * Module
 * Monoid
 * Quasigroup
 * Rig
 * Ring
 * Ringoid
 * Semigroup
 * Semiring

This is a decent foundation and we can tweak or add other things (`Lattice` and friends) later. I can also sketch out the relationships between these, if you like (though it's all available above in the stated references). For example, `Semigroup` is a `Magma`, and so forth.

**Comment by vmarquez** [comment]
@jdegoes I'm most interested in SemiLattice, does that not belong on the list?

**Comment by TomasMikula** [comment]
I'm also more interested in lattice-like structures than ring-like structures.

**Comment by jdegoes** [comment]
@vmarquez @TomasMikula I think we need them all, but we need to start somewhere. 😄

**Comment by caente** [comment]
@jdegoes I'll make a first stab at this tomorrow, it will probably be lacking, but I don't think I'll need anything else yet, between Kmett's code and Pinter's book I _could_ be fine.

**Comment by garyb** [comment]
@vmarquez @jdegoes If you add `Idempotent` you can get `Band` (Semigroup + Idempotent) and then `Semilattice` (Commutative + Band).

**Comment by jdegoes** [comment]
@caente Awesome, let me know if you run into any trouble!

@garyb Hehe. Thanks. Good to see you around these parts! 😄

**Comment by fommil** [comment]
What about a decent test library? It's still an open gap in FP... imagine a suite of matchers like scalatest that uses Equal and Order, and maybe even a "choose your Monad" runner so you could write Id tests, Either tests, or IO tests. With structural diffs of things that don't match the expectations. Maybe even macros to easily create "mock" versions of a finally tagless algebra backed by an mvar.

**Comment by tonymorris** [comment]
If you are going to do a decent test library, look at hedgehog.

https://hackage.haskell.org/package/hedgehog

Don't copy quickcheck/scalacheck. You'll be way ahead of anything else that exists for Scala.

IMO.

**Comment by caente** [comment]
@jdegoes @vmarquez @garyb @TomasMikula @puffnfresh I oppened this PR https://github.com/scalaz/scalaz/pull/1551 to move the conversation there, if possible I rather add small changes at a time. 
Do let me know if you think we should start a "lower level".

**Comment by NeQuissimus** [comment]
@tonymorris @fommil I would be very interested in this actually. I just figured it would be beyond the Scalaz 8 scope. There is [scala-dedgehog](https://github.com/hedgehogqa/scala-hedgehog) but I have never used it. In #1540 @jdegoes mentioned that ScalaProps is meant to become part of Scalaz 8, we should definitely keep that in mind.

**Comment by jdegoes** [comment]
@NeQuissimus @tonymorris Indeed, Hedgehog is my favorite too. ScalaProps is closer than ScalaCheck and can be made closer still, so it's a good base.

**Comment by jdegoes** [comment]
@fommil It's needed. All the test libraries are non-functional and do not understand functional concepts (e.g. Monad), which makes them difficult to use. Something small but fully integrated into Scalaz can be used for internal tests, but also as a dependency `scalaz-test` in other projects.

**Comment by edmundnoble** [comment]
https://github.com/scalaz/testz is now up. It needs Hedgehog-style property-based testing, but for now it should at least let us write laws.

**Comment by Atry** [comment]
> While the type classes are essential, the dirty secret in Scala is that actual monad transformers do not perform well and are not a realistic solution for most code. An alternative to stacks of monad transformers that is better suited to Scala must be developed.

In fact, `Codensity` performs pretty good in Scala, and because continuation is the mother of all monads, it is easy to implement MTL MonadXxx type class instances with specialized `Codensity`s.
