### ISSUE TITLE
Scalaz 7.3

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1893]
We should decide on the priorities before moving 7.3 into RC.

These are the things I'd personally like to see done before we do that. @xuwei-k is there anything you'd like to add to the list? (please edit this comment to add things)

- [ ] instances for zio (and deleting `scalaz.effect` / generally removing anything that handles `Throwable`) https://github.com/scalaz/scalaz/issues/1796
- [ ] more instances for `Derives` https://github.com/scalaz/scalaz/issues/1885
- [ ] removing covariant / contravariant type parameters  https://github.com/scalaz/scalaz/issues/1892
- [ ] converting as many traits to abstract classes as possible (for bincompat)
- [ ] converting as many data types as possible to actual ADTs instead of the legacy anonymous class encoding
- [ ] add `Alternative` and corresponding methods (like the `psum`) to `Foldable` https://github.com/scalaz/scalaz/issues/1884
- [ ] a few other things tagged as scalaz7 (we should close things we don't think we can do) https://github.com/scalaz/scalaz/issues?q=is%3Aopen+is%3Aissue+author%3Afommil+label%3Ascalaz7

**Comment by rabbitonweb** [comment]
could those be evantually tickets labeled with `scalaz7.3` ?

**Comment by fommil** [comment]
@rabbitonweb the scalaz7 is basically just so the scalaz8 folk can ignore them :smile:

**Comment by fommil** [comment]
I recently added `Arbitrary` to `scalaz-deriving` e.g. upgrade the `Monad` in `ScalaCheckBinding` to

```scala
    override def altly2[Z, A1, A2](a1: =>Arbitrary[A1], a2: =>Arbitrary[A2])(
      f: A1 \/ A2 => Z
    ): Arbitrary[Z] = Arbitrary {
      Gen
        .oneOf(
          Gen.lzy(a1.arbitrary.map(-\/(_))),
          Gen.lzy(a2.arbitrary.map(\/-(_)))
        )
        .map(f)
    }
```

Although I am dubious about what laws this will satisfy. At a casual reading it appears to break RT for altly2, altly3, etc, since the leftmost element will be selected the most. @alexarchambault how did you solve this?

and, since we can,

```
    override def apply2[A1, A2, Z](a1: =>Arbitrary[A1], a2: =>Arbitrary[A2])(
      f: (A1, A2) => Z
    ): Arbitrary[Z] = Arbitrary {
      for {
        a <- a1.arbitrary
        b <- a2.arbitrary
      } yield f(a, b)
    }
```

Cogen could have a Decidable.

**Comment by alexarchambault** [comment]
@fommil In scalacheck-shapeless, I use `Gen.frequency` to give the right weight to the two elements of the sum type. Like in `H :+: T`, I give a weight of 1 to `H`, and of len(T) to `T`.

**Comment by fommil** [comment]
oh interesting! I do not know if I have access to that information. It would be good if `Gen` was able to carry such information.
